name: 'add-label'
description: 'Display the PR title and comment'
inputs:
configuration-path:
    description: 'The path for the add-label configurations'
    default: '.github/label_config.yml'
    required: false
    
runs:
  using: 'node12'
  main: 'index.js'
