on: [pull_request]

jobs:
  label_my_pr_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Display PR title
      uses: ./
      with:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        CONFIG_PATH: '../Label_config.yml'
        
